name: Pomodoro
description: A pomodoro timer

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.5.0+12

environment:
  sdk: ">3.4.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.2
  audioplayers: ^6.0.0
  firebase_messaging: ^15.0.3
  firebase_core: ^3.2.0
  flutter_local_notifications: ^17.2.1+2
  wakelock: ^0.6.1+2
  shared_preferences: ^2.0.13
  firebase_analytics: ^11.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"

flutter:

  uses-material-design: true

  assets:
    - assets/alarm.mp3
