name: Pomodoro
description: A pomodoro timer

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.0

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.2
  audioplayers: ^0.20.1
  firebase_messaging: ^11.3.0
  firebase_core: ^1.16.0
  flutter_local_notifications: ^9.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"

flutter:

  uses-material-design: true

  assets:
    - assets/alarm.mp3
