// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRiL4-Tkpi_ulNTq_JEyt84s8fempFU4M',
    appId: '1:711277251650:android:6a90af90f07dabf26831db',
    messagingSenderId: '711277251650',
    projectId: 'pomodoro-f473f',
    storageBucket: 'pomodoro-f473f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWMfXoOCv28ezkHuNLwjsgZFTAhrEWE7Q',
    appId: '1:711277251650:ios:d19fbfd201fcc8ac6831db',
    messagingSenderId: '711277251650',
    projectId: 'pomodoro-f473f',
    storageBucket: 'pomodoro-f473f.appspot.com',
    iosClientId: '711277251650-kpi5qck63lkhjjidl4m2qg2aj166pj3b.apps.googleusercontent.com',
    iosBundleId: 'com.cchampou.pomo.pomodoro',
  );
}
