name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout from version control
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
        name: Setup Flutter
      - run: flutter pub get
        name: Get dependencies
      - run: |
          echo keyPassword=\${{ secrets.KEY_STORE }} > ${{env.PROPERTIES_PATH}}
          echo storePassword=\${{ secrets.KEY_PASSWORD }} >> ${{env.PROPERTIES_PATH}}
          echo keyAlias=\${{ secrets.KEY_ALIAS }} >> ${{env.PROPERTIES_PATH}}
          echo storeFile=\${{ env.KEYSTORE_FILE }} >> ${{env.PROPERTIES_PATH}}
        name: Generate key file
      - run: echo "${{ secrets.KEYSTORE2 }}" | base64 --decode > ${{ env.KEYSTORE_PATH }}
        name: Extract keystore file
      - run: flutter build appbundle
        name: Build Android bundle
      - name: Publish Android bundle
        uses: actions/upload-artifact@v3
        with:
          name: Android bundle
          path: build/app/outputs/bundle/release/app-release.aab

env:
  PROPERTIES_PATH: "./android/key.properties"
  KEYSTORE_PATH: "./android/app/key.jks"
  KEYSTORE_FILE "./key.jks"
