name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout from version control
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
        name: Setup Flutter
      - run: flutter pub get
        name: Get dependencies
      - run: flutter build appbundle
        name: Build Android bundle
      - name: Publish Android bundle
        uses: actions/upload-artifact@v3
        with:
          name: Android bundle
          path: build/app/outputs/bundle/release/app-release.aab
